In [2]:
# Importing basic lib

import pandas as pd
import numpy as np

In [3]:
# Import data from your local system 

Data = pd.read_excel("File path ")

In [4]:
# Cross checking if Data is imported

Data

     Input     Output
0    6.1101  17.59200
1    5.5277   9.13020
2    8.5186  13.66200
3    7.0032  11.85400
4    5.8598   6.82330
5    8.3829  11.88600
6    7.4764   4.34830
7    8.5781  12.00000
8    6.4862   6.59870
9    5.0546   3.81660
10   5.7107   3.25220
11  14.1640  15.50500
12   5.7340   3.15510
13   8.4084   7.22580
14   5.6407   0.71618
15   5.3794   3.51290
16   6.3654   5.30480
17   5.1301   0.56077
18   6.4296   3.65180
19   7.0708   5.38930
20   6.1891   3.13860
21  20.2700  21.76700
22   5.4901   4.26300
23   6.3261   5.18750
24   5.5649   3.08250
25  18.9450  22.63800
26  12.8280  13.50100
27  10.9570   7.04670
28  13.1760  14.69200
29  22.2030  24.14700
..      ...       ...
67  10.2360   7.77540
68   5.4994   1.01730
69  20.3410  20.99200
70  10.1360   6.67990
71   7.3345   4.02590
72   6.0062   1.27840
73   7.2259   3.34110
74   5.0269  -2.68070
75   6.5479   0.29678
76   7.5386   3.88450
77   5.0365   5.70140
78  10.2740   6.75260
79   5.1077   2.05760
80   5.7292   0.47953
81   5.1884   0.20421
82   6.3557   0.67861
83   9.7687   7.54350
84   6.5159   5.34360
85   8.5172   4.24150
86   9.1802   6.79810
87   6.0020   0.92695
88   5.5204   0.15200
89   5.0594   2.82140
90   5.7077   1.84510
91   7.6366   4.29590
92   5.8707   7.20290
93   5.3054   1.98690
94   8.2934   0.14454
95  13.3940   9.05510
96   5.4369   0.61705

[97 rows x 2 columns]

In [16]:
# Spliting of data as input and output

X = Data.iloc[:, :1].values
y = Data.iloc[:, 1:2].values

array([[  6.1101],
       [  5.5277],
       [  8.5186],
       [  7.0032],
       [  5.8598],
       [  8.3829],
       [  7.4764],
       [  8.5781],
       [  6.4862],
       [  5.0546],
       [  5.7107],
       [ 14.164 ],
       [  5.734 ],
       [  8.4084],
       [  5.6407],
       [  5.3794],
       [  6.3654],
       [  5.1301],
       [  6.4296],
       [  7.0708],
       [  6.1891],
       [ 20.27  ],
       [  5.4901],
       [  6.3261],
       [  5.5649],
       [ 18.945 ],
       [ 12.828 ],
       [ 10.957 ],
       [ 13.176 ],
       [ 22.203 ],
       [  5.2524],
       [  6.5894],
       [  9.2482],
       [  5.8918],
       [  8.2111],
       [  7.9334],
       [  8.0959],
       [  5.6063],
       [ 12.836 ],
       [  6.3534],
       [  5.4069],
       [  6.8825],
       [ 11.708 ],
       [  5.7737],
       [  7.8247],
       [  7.0931],
       [  5.0702],
       [  5.8014],
       [ 11.7   ],
       [  5.5416],
       [  7.5402],
       [  5.3077],
       [  7.4239],
       [  7.6031],
       [  6.3328],
       [  6.3589],
       [  6.2742],
       [  5.6397],
       [  9.3102],
       [  9.4536],
       [  8.8254],
       [  5.1793],
       [ 21.279 ],
       [ 14.908 ],
       [ 18.959 ],
       [  7.2182],
       [  8.2951],
       [ 10.236 ],
       [  5.4994],
       [ 20.341 ],
       [ 10.136 ],
       [  7.3345],
       [  6.0062],
       [  7.2259],
       [  5.0269],
       [  6.5479],
       [  7.5386],
       [  5.0365],
       [ 10.274 ],
       [  5.1077],
       [  5.7292],
       [  5.1884],
       [  6.3557],
       [  9.7687],
       [  6.5159],
       [  8.5172],
       [  9.1802],
       [  6.002 ],
       [  5.5204],
       [  5.0594],
       [  5.7077],
       [  7.6366],
       [  5.8707],
       [  5.3054],
       [  8.2934],
       [ 13.394 ],
       [  5.4369]])

In [17]:
# Creating a column of ones and inserting to x

ones = np.ones((97,1))
X = np.insert(X, [0], ones, axis =1)

In [9]:
# Creating initial 2X1 matrix of thetas

theta = np.zeros((2,1))

In [18]:
# Build a function to calculate Cost Function

def costfunction(X, y, theta):
    prediction = np.matmul(X, theta)
    sqerror = np.square(np.subtract(prediction, y))
    sum = np.array(sqerror).sum()
    J = 1/194*sum
    
    return J

In [22]:
# Build a function to calculate Gradient Descent

def gradientdescent (X, y, alpha, theta):
    tetha = np.zeros((2,1))
    for i in range(1500):
        prediction = np.matmul(X, theta)
        error1 = np.subtract(prediction, y)
        error2 = (np.subtract(prediction, y))*X[:, 1:2]
        
        sum1 = np.array(error1).sum()
        sum2 = np.array(error2).sum()
        
        temp0 = theta[0:1, 0:1] - ((alpha/97) * (sum1))
        temp1 = theta[1:2, 0:1] - ((alpha/97) * (sum2))
        
        theta[0:1, 0:1] = temp0 # Simultaneously updating theta
        theta[1:2, 0:1] = temp1
        
    return theta

In [36]:
# Check values for CF and GD

CF = costfunction(X, y, np.array([[-9], [3]]))
GD = gradientdescent(X, y, 0.01, theta)

print("Cost Funcation is : \n", CF)
print("\n Tetha values are : \n", GD)

Cost Funcation is :
 75.141542804

 Tetha values are :
 [[-3.89578088]
 [ 1.19303364]]